[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/systray"

[[constraint]]
  name = "github.com/emersion/go-imap"
  version = "0.9.0"
